"""Original Pollik OS icons and cursors. Procedural vector shapes, no external artwork."""
from pathlib import Path
from PIL import Image, ImageDraw
import math

ROOT=Path(__file__).resolve().parents[1]
S=4

def rr(d,box,r,color): d.rounded_rectangle(tuple(int(v*S) for v in box),int(r*S),fill=color)
def line(d,pts,color,width): d.line([(int(x*S),int(y*S)) for x,y in pts],fill=color,width=int(width*S),joint='curve')
def poly(d,pts,color): d.polygon([(int(x*S),int(y*S)) for x,y in pts],fill=color)

def icon(kind):
    im=Image.new('RGBA',(72*S,72*S))
    mask=Image.new('L',im.size);rr(ImageDraw.Draw(mask),(1,1,71,71),19,255)
    pairs=[((166,125,255),(94,72,202)),((117,210,255),(50,129,231)),((78,86,112),(30,35,55)),((255,248,219),(246,229,177)),((226,233,245),(155,171,194))]
    a,b=pairs[kind]
    d=ImageDraw.Draw(im)
    for y in range(72*S):
        t=y/(72*S);d.line((0,y,72*S,y),fill=tuple(round(a[k]*(1-t)+b[k]*t) for k in range(3))+(255,))
    im.putalpha(mask);d=ImageDraw.Draw(im)
    if kind==0:
        rr(d,(22,16,30,56),4,'#ffffff');rr(d,(26,16,53,40),11,'#ffffff');rr(d,(30,23,45,33),5,'#9f80ec')
        rr(d,(40,46,55,55),4,'#d3bdff')
    if kind==1:
        rr(d,(12,19,34,32),5,'#d3efff');rr(d,(12,25,60,56),6,'#b0dfff')
        rr(d,(14,30,59,58),6,'#f0faff');line(d,[(20,37),(53,37)],'#d1eafd',2)
        rr(d,(35,45,54,50),2,'#80b8ef')
    if kind==2:
        rr(d,(10,15,62,57),8,'#171e30');rr(d,(14,19,17,22),1,'#f28a91');rr(d,(20,19,23,22),1,'#f0cd89');rr(d,(26,19,29,22),1,'#80c7ae')
        line(d,[(21,32),(30,40),(21,48)],'#eef6ff',3);line(d,[(37,49),(50,49)],'#b5c3e4',3)
    if kind==3:
        rr(d,(15,10,56,61),6,'#ffffff');rr(d,(15,10,56,23),5,'#f5c44f')
        for y,w in [(31,26),(39,23),(47,18)]:line(d,[(22,y),(22+w,y)],'#c3c7d1',2)
        poly(d,[(43,54),(59,31),(65,35),(49,58)],'#5b91be');poly(d,[(43,54),(43,61),(49,58)],'#334a64')
    if kind==4:
        pts=[]
        for j in range(48):
            a=math.pi*2*j/48;r=25 if j%4 in (1,2) else 20
            pts.append((36+math.cos(a)*r,36+math.sin(a)*r))
        poly(d,pts,'#f8fbff');rr(d,(21,21,51,51),15,'#798ba5');rr(d,(26,26,46,46),10,'#d7e1ef');rr(d,(31,31,41,41),5,'#8ea1ba')
    return im.resize((72,72),Image.Resampling.LANCZOS)

def cursor(kind):
    im=Image.new('RGBA',(32*S,36*S));d=ImageDraw.Draw(im)
    if kind==0:
        outer=[(2,1),(2,27),(9,21),(14,33),(20,30),(15,19),(25,19)]
        inner=[(4,5),(4,23),(10,18),(15,30),(17,29),(12,17),(20,17)]
        poly(d,outer,'#ffffff');poly(d,inner,'#242634')
    elif kind==1:
        line(d,[(11,3),(17,3),(14,6),(14,25),(11,28),(17,28)],'#ffffff',4)
        line(d,[(11,3),(17,3)],'#292938',2);line(d,[(14,3),(14,28)],'#292938',2);line(d,[(11,28),(17,28)],'#292938',2)
    else:
        rr(d,(9,3,16,24),3,'#ffffff');rr(d,(9,12,25,31),6,'#ffffff')
        rr(d,(5,16,13,27),3,'#ffffff');rr(d,(11,5,14,22),1,'#303342')
        line(d,[(8,20),(12,25),(12,28),(22,28),(23,17)],'#303342',2)
    return im.resize((32,36),Image.Resampling.LANCZOS)

def custom_icon(kind):
    files = ['AboutSystemIcon.png', 'FilesIcon.png', 'TerminalIcon.png', 'NotepadIcon.png', 'SettingsIcon.png', 'BrowserIcon.png']
    path = ROOT / 'assets' / files[kind]
    im = Image.open(path).convert('RGBA')
    return im.resize((72, 72), Image.Resampling.LANCZOS)

out=['/* Generated by assets/build_ui.py. Original indexed RGBA artwork. */']
for name,images in [('icons',[custom_icon(i) for i in range(6)]),('cursors',[cursor(i) for i in range(3)])]:
    palettes=[];indices=[];alphas=[]
    for im in images:
        r, g, b, a = im.split()
        bg_col = (112, 50, 251) if name == 'icons' else (36, 38, 52)
        bg = Image.new('RGB', im.size, bg_col)
        clean_rgb = Image.composite(Image.merge('RGB', (r, g, b)), bg, a)
        q = clean_rgb.quantize(colors=256, method=Image.Quantize.MAXCOVERAGE)
        p = q.getpalette('RGB'); p += [0] * (768 - len(p))
        palettes.append([0xff000000 | p[i] << 16 | p[i+1] << 8 | p[i+2] for i in range(0, 768, 3)])
        indices.append(list(q.tobytes()))
        alpha_vals = [round(v * 15 / 255) for v in a.tobytes()]
        alphas.append([(alpha_vals[i] << 4) | alpha_vals[i+1] for i in range(0, len(alpha_vals), 2)])
    out.append(f'static const u32 {name}_palette[{len(images)}][256]={{')
    out.extend('{'+','.join(hex(v) for v in row)+'},' for row in palettes);out.append('};')
    out.append(f'static const u8 {name}_index[{len(images)}][{images[0].width*images[0].height}]={{')
    out.extend('{'+','.join(str(v) for v in row)+'},' for row in indices);out.append('};')
    out.append(f'static const u8 {name}_alpha[{len(images)}][{images[0].width*images[0].height//2}]={{')
    out.extend('{'+','.join(str(v) for v in row)+'},' for row in alphas);out.append('};')
(ROOT/'kernel/ui_data.h').write_text('\n'.join(out)+'\n')
preview=Image.new('RGBA',(500,130),'#eeebf5')
for i in range(5):preview.alpha_composite(custom_icon(i),(20+i*88,25))
preview.save(ROOT/'assets/icons.png')
print('Generated five custom icons and three antialiased cursors.')
