"""Original Pollik OS icons and cursors. Procedural vector shapes and high-res icon assets."""
from pathlib import Path
from PIL import Image, ImageDraw
import math

ROOT=Path(__file__).resolve().parents[1]
S=4

def rr(d,box,r,color): d.rounded_rectangle(tuple(int(v*S) for v in box),int(r*S),fill=color)
def line(d,pts,color,width): d.line([(int(x*S),int(y*S)) for x,y in pts],fill=color,width=int(width*S),joint='curve')
def poly(d,pts,color): d.polygon([(int(x*S),int(y*S)) for x,y in pts],fill=color)

def cursor(kind):
    im=Image.new('RGBA',(32*S,36*S));d=ImageDraw.Draw(im)
    if kind==0:
        outer=[(2,1),(2,27),(9,21),(14,33),(20,30),(15,19),(25,19)]
        inner=[(4,5),(4,23),(10,18),(15,30),(17,29),(12,17),(20,17)]
        poly(d,outer,'#ffffff');poly(d,inner,'#242634')
    elif kind==1:
        line(d,[(11,3),(17,3),(14,6),(14,25),(11,28),(17,28)],'#ffffff',4)
        line(d,[(11,3),(17,3)],'#292938',2);line(d,[(14,3),(14,28)],'#292938',2);line(d,[(11,28),(17,28)],'#292938',2)
    else:
        rr(d,(9,3,16,24),3,'#ffffff');rr(d,(9,12,25,31),6,'#ffffff')
        rr(d,(5,16,13,27),3,'#ffffff');rr(d,(11,5,14,22),1,'#303342')
        line(d,[(8,20),(12,25),(12,28),(22,28),(23,17)],'#303342',2)
    return im.resize((32,36),Image.Resampling.LANCZOS)

def custom_icon(kind):
    files = ['AboutSystemIcon.png', 'FilesIcon.png', 'TerminalIcon.png', 'NotepadIcon.png', 'SettingsIcon.png', 'BrowserIcon.png']
    path = ROOT / 'assets' / files[kind]
    im = Image.open(path).convert('RGBA')
    return im.resize((72, 72), Image.Resampling.LANCZOS)

def desktop_icon(kind):
    files = ['FolderIcon.png', 'TextFileIcon.png', 'TrashIcon.png', 'FolderBlueIcon.png']
    path = ROOT / 'assets' / files[kind]
    im = Image.open(path).convert('RGBA')
    return im.resize((72, 72), Image.Resampling.LANCZOS)

out=['/* Generated by assets/build_ui.py. High-res indexed RGBA artwork. */']
groups = [
    ('icons', [custom_icon(i) for i in range(6)]),
    ('desktop_icons', [desktop_icon(i) for i in range(4)]),
    ('cursors', [cursor(i) for i in range(3)])
]

for name, images in groups:
    palettes=[];indices=[];alphas=[]
    for im in images:
        r, g, b, a = im.split()
        bg_col = (15, 23, 42) if name in ('icons', 'desktop_icons') else (36, 38, 52)
        bg = Image.new('RGB', im.size, bg_col)
        clean_rgb = Image.composite(Image.merge('RGB', (r, g, b)), bg, a)
        q = clean_rgb.quantize(colors=256, method=Image.Quantize.MAXCOVERAGE)
        p = q.getpalette('RGB'); p += [0] * (768 - len(p))
        palettes.append([0xff000000 | p[i] << 16 | p[i+1] << 8 | p[i+2] for i in range(0, 768, 3)])
        indices.append(list(q.tobytes()))
        alpha_vals = [round(v * 15 / 255) for v in a.tobytes()]
        alphas.append([(alpha_vals[i] << 4) | alpha_vals[i+1] for i in range(0, len(alpha_vals), 2)])
    out.append(f'static const u32 {name}_palette[{len(images)}][256]={{')
    out.extend('{'+','.join(hex(v) for v in row)+'},' for row in palettes);out.append('};')
    out.append(f'static const u8 {name}_index[{len(images)}][{images[0].width*images[0].height}]={{')
    out.extend('{'+','.join(str(v) for v in row)+'},' for row in indices);out.append('};')
    out.append(f'static const u8 {name}_alpha[{len(images)}][{images[0].width*images[0].height//2}]={{')
    out.extend('{'+','.join(str(v) for v in row)+'},' for row in alphas);out.append('};')

(ROOT/'kernel/ui_data.h').write_text('\n'.join(out)+'\n')

preview = Image.new('RGBA', (880, 110), '#0f172a')
draw = ImageDraw.Draw(preview)
for i in range(6):
    preview.alpha_composite(custom_icon(i), (16 + i * 84, 20))
for i in range(4):
    preview.alpha_composite(desktop_icon(i), (524 + i * 84, 20))
preview.save(ROOT/'assets/icons.png')
print('Generated 6 app icons, 4 desktop icons, and 3 antialiased cursors in kernel/ui_data.h.')
