"""Pinned NetSurf parsers, native static libraries and reproducible generators."""
from pathlib import Path
import argparse,subprocess,shutil
ROOT=Path(__file__).resolve().parents[1]
NAMES=('libparserutils','libwapcaplet','libhubbub','libdom','libcss')
def build(output,native):
    output=Path(output).resolve();output.mkdir(parents=True,exist_ok=True)
    git=Path(shutil.which('git') or 'git')
    perl=shutil.which('perl') or str(git.parent.parent/'usr/bin/perl.exe')
    for name,script in [('libparserutils','make-aliases.pl'),('libhubbub','make-entities.pl')]:
        subprocess.run([perl,'build/'+script],cwd=ROOT/'third_party'/name,check=True)
    # Same upstream keyword data; deterministic bounded binary lookup avoids
    # requiring a separate gperf installation on Windows.
    tree=ROOT/'third_party/libhubbub/src/treebuilder'
    words=[];data=(tree/'element-type.gperf').read_text().split('%%',1)[1]
    for line in data.splitlines():
        if ',' in line:
            name,kind=line.split(',',1);words.append((name.strip(),kind.strip()))
    code=['/* Generated from the pinned MIT-licensed element-type.gperf. */',
          'static const struct element_type_map wordlist[]={']
    code += ['{"'+name+'",'+kind+'},' for name,kind in sorted(words)]
    code += ['};','static const struct element_type_map *hubbub_element_type_generated_lookup(const char *s,size_t n){',
             'size_t lo=0,hi=sizeof(wordlist)/sizeof(wordlist[0]);while(lo<hi){size_t mid=lo+(hi-lo)/2;',
             'const char *w=wordlist[mid].name;size_t i=0;int d=0;for(;i<n&&w[i];++i){unsigned char c=(unsigned char)s[i];if(c>=65&&c<=90)c+=32;d=(int)c-(unsigned char)w[i];if(d)break;}',
             'if(!d)d=i<n?1:w[i]?-1:0;if(!d)return &wordlist[mid];if(d<0)hi=mid;else lo=mid+1;}return NULL;}']
    (tree/'autogenerated-element-type.c').write_text('\n'.join(code)+'\n')
    generator=output/'css_generator.exe'
    subprocess.run(['clang','-D_CRT_SECURE_NO_WARNINGS','-Dstrdup=_strdup',
                    'third_party/libcss/src/parse/properties/css_property_parser_gen.c','-o',str(generator)],cwd=ROOT,check=True)
    properties=ROOT/'third_party/libcss/src/parse/properties'
    for line in (properties/'properties.gen').read_text().splitlines():
        if line and not line.startswith('#') and ':' in line:
            name=line.split(':',1)[0]
            subprocess.run([str(generator),'-o',str(properties/('autogenerated_'+name+'.c')),line],check=True)
    flags=['-O2','-DNDEBUG','-D_BSD_SOURCE','-D_DEFAULT_SOURCE','-DWITHOUT_ICONV_FILTER',
           '-ffunction-sections','-fdata-sections']
    if native:flags+=['--target=x86_64-none-elf','-ffreestanding','-fno-builtin','-fno-pic','-fno-pie',
        '-fno-stack-protector','-mno-red-zone','-mcmodel=large','-msse2','-mno-avx',
        '-fno-vectorize','-fno-slp-vectorize','-Isdk/include']
    else:flags+=['-D_CRT_SECURE_NO_WARNINGS']
    for name in NAMES:flags+=['-Ithird_party/'+name+'/include']
    archives=[]
    for name in NAMES:
        library=ROOT/'third_party'/name;objects=[];target=output/name;target.mkdir(exist_ok=True)
        sources=list((library/'src').rglob('*.c'))
        if name=='libdom':sources+=list((library/'bindings/hubbub').glob('*.c'))
        for source in sorted(sources):
            if source.name in ('css_property_parser_gen.c','autogenerated-element-type.c'):continue
            obj=target/(source.relative_to(library).as_posix().replace('/','_')+'.o')
            command=['clang',*flags,'-I'+str(library/'src'),'-I'+str(library/'bindings'),'-c',str(source),'-o',str(obj)]
            print('COMMAND '+subprocess.list2cmdline(command),flush=True)
            subprocess.run(command,cwd=ROOT,check=True);objects.append(str(obj))
        archive=output/(name+'.a');subprocess.run(['llvm-ar','rcs',str(archive),*objects],check=True)
        print(f'WEB_LIBRARY {name} objects={len(objects)} bytes={archive.stat().st_size}',flush=True)
        archives.append(archive)
    return archives
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--output',required=True);parser.add_argument('--native',action='store_true')
    args=parser.parse_args();build(args.output,args.native)
