"""Pinned NetSurf parsers, native static libraries and reproducible generators."""
from pathlib import Path
import argparse,subprocess,shutil,hashlib,json
ROOT=Path(__file__).resolve().parents[1]
NAMES=('libparserutils','libwapcaplet','libhubbub','libdom','libcss')
def generate(output):
    properties=ROOT/'third_party/libcss/src/parse/properties'
    descriptors=[line for line in (properties/'properties.gen').read_text().splitlines()
                 if line and not line.startswith('#') and ':' in line]
    generated=[properties/('autogenerated_'+line.split(':',1)[0]+'.c') for line in descriptors]
    generated += [ROOT/'third_party/libparserutils/src/charset/aliases.inc',
                  ROOT/'third_party/libhubbub/src/tokeniser/entities.inc',
                  ROOT/'third_party/libhubbub/src/treebuilder/autogenerated-element-type.c']
    inputs=[Path(__file__),properties/'properties.gen',properties/'css_property_parser_gen.c',
            ROOT/'third_party/libparserutils/build/make-aliases.pl',ROOT/'third_party/libparserutils/build/Aliases',
            ROOT/'third_party/libhubbub/build/make-entities.pl',ROOT/'third_party/libhubbub/build/Entities',
            ROOT/'third_party/libhubbub/src/treebuilder/element-type.gperf']
    digest=hashlib.sha256()
    for source in inputs:digest.update(source.read_bytes())
    key=digest.hexdigest();stamp=ROOT/'build/web-generators.json'
    def fingerprints():
        return {p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in generated}
    if stamp.exists() and all(p.exists() for p in generated):
        try:
            cached=json.loads(stamp.read_text())
            if cached.get('input')==key and cached.get('outputs')==fingerprints():return
        except (ValueError,OSError):pass
    git=Path(shutil.which('git') or 'git')
    perl=shutil.which('perl') or str(git.parent.parent/'usr/bin/perl.exe')
    for name,script in [('libparserutils','make-aliases.pl'),('libhubbub','make-entities.pl')]:
        subprocess.run([perl,'build/'+script],cwd=ROOT/'third_party'/name,check=True)
    # Same upstream keyword data; deterministic bounded binary lookup avoids
    # requiring a separate gperf installation on Windows.
    tree=ROOT/'third_party/libhubbub/src/treebuilder'
    words=[];data=(tree/'element-type.gperf').read_text().split('%%',1)[1]
    for line in data.splitlines():
        if ',' in line:
            name,kind=line.split(',',1);words.append((name.strip(),kind.strip()))
    code=['/* Generated from the pinned MIT-licensed element-type.gperf. */',
          'static const struct element_type_map wordlist[]={']
    code += ['{"'+name+'",'+kind+'},' for name,kind in sorted(words)]
    code += ['};','static const struct element_type_map *hubbub_element_type_generated_lookup(const char *s,size_t n){',
             'size_t lo=0,hi=sizeof(wordlist)/sizeof(wordlist[0]);while(lo<hi){size_t mid=lo+(hi-lo)/2;',
             'const char *w=wordlist[mid].name;size_t i=0;int d=0;for(;i<n&&w[i];++i){unsigned char c=(unsigned char)s[i];if(c>=65&&c<=90)c+=32;d=(int)c-(unsigned char)w[i];if(d)break;}',
             'if(!d)d=i<n?1:w[i]?-1:0;if(!d)return &wordlist[mid];if(d<0)hi=mid;else lo=mid+1;}return NULL;}']
    (tree/'autogenerated-element-type.c').write_text('\n'.join(code)+'\n')
    # Invoke the unmodified upstream generator repeatedly within one host
    # process. Starting 119 separate executables is costly on Windows.
    wrapper=output/'css_generator_batch.c'
    upstream=(properties/'css_property_parser_gen.c').as_posix()
    wrapper.write_text('#define main property_main\n#include "'+upstream+'"\n#undef main\n'+r'''
int main(int argc,char **argv) {
    if(argc!=3)return 1;
    FILE *input=fopen(argv[2],"r");if(!input)return 2;
    char line[8192],path[4096];int result=0;
    while(fgets(line,sizeof(line),input)) {
        size_t n=strlen(line);if(n && line[n-1]=='\n')line[--n]=0;
        if(n && line[n-1]=='\r')line[--n]=0;
        if(!n || line[0]=='#')continue;
        char *colon=strchr(line,':');if(!colon){result=3;break;}
        *colon=0;int written=snprintf(path,sizeof(path),"%s/autogenerated_%s.c",argv[1],line);*colon=':';
        if(written<0 || (size_t)written>=sizeof(path)){result=4;break;}
        char *args[]={argv[0],"-o",path,line,NULL};result=property_main(4,args);if(result)break;
    }
    if(ferror(input))result=5;
    fclose(input);return result;
}
''')
    generator=output/'css_generator_batch.exe'
    subprocess.run(['clang','-D_CRT_SECURE_NO_WARNINGS','-Dstrdup=_strdup',
                    str(wrapper),'-o',str(generator)],cwd=ROOT,check=True)
    subprocess.run([str(generator),str(properties),str(properties/'properties.gen')],check=True)
    stamp.write_text(json.dumps({'input':key,'outputs':fingerprints()},sort_keys=True))
def build(output,native):
    output=Path(output).resolve();output.mkdir(parents=True,exist_ok=True)
    generate(output)
    flags=['-O2','-DNDEBUG','-D_BSD_SOURCE','-D_DEFAULT_SOURCE','-DWITHOUT_ICONV_FILTER',
           '-D_ALIGNED=__attribute__((aligned(8)))','-ffunction-sections','-fdata-sections']
    if native:flags+=['--target=x86_64-none-elf','-ffreestanding','-fno-builtin','-fno-pic','-fno-pie',
        '-fno-stack-protector','-mno-red-zone','-mcmodel=large','-msse2','-mno-avx',
        '-fno-vectorize','-fno-slp-vectorize','-Isdk/include']
    else:flags+=['-D_CRT_SECURE_NO_WARNINGS']
    for name in NAMES:flags+=['-Ithird_party/'+name+'/include']
    digest=hashlib.sha256(json.dumps(flags).encode())
    inputs=list((ROOT/'sdk/include').rglob('*.h')) if native else []
    for name in NAMES:
        inputs+=list((ROOT/'third_party'/name/'include').rglob('*.h'))
        inputs+=[p for p in (ROOT/'third_party'/name/'src').rglob('*') if p.is_file() and p.suffix in ('.h','.c','.inc')]
        if name=='libdom':inputs+=list((ROOT/'third_party'/name/'bindings/hubbub').glob('*'))
    for source in sorted(set(p for p in inputs if p.is_file())):
        digest.update(source.relative_to(ROOT).as_posix().encode());digest.update(source.read_bytes())
    key=digest.hexdigest();stamp=output/('native.stamp' if native else 'host.stamp')
    archives=[output/(name+'.a') for name in NAMES]
    if stamp.exists() and stamp.read_text()==key and all(p.exists() for p in archives):
        print('WEB_LIBRARIES cached: pinned sources, generated parsers and SDK headers unchanged',flush=True)
        return archives
    # The key includes target/compiler flags and every SDK/upstream input.
    # Reuse identical native archives across normal, production and test builds.
    candidates=[ROOT/'build/browser-upstream']+[ROOT/'build/x86_64'/variant/'web' for variant in ('kernel','system','selftest')]
    for candidate in candidates:
        previous=candidate/stamp.name
        if candidate.resolve()!=output and previous.exists() and previous.read_text()==key and all((candidate/(name+'.a')).exists() for name in NAMES):
            for name in NAMES:shutil.copyfile(candidate/(name+'.a'),output/(name+'.a'))
            stamp.write_text(key)
            print('WEB_LIBRARIES reused identical native archives from '+str(candidate),flush=True)
            return archives
    archives=[]
    for name in NAMES:
        library=ROOT/'third_party'/name;objects=[];target=output/name;target.mkdir(exist_ok=True)
        sources=list((library/'src').rglob('*.c'))
        if name=='libdom':sources+=list((library/'bindings/hubbub').glob('*.c'))
        for source in sorted(sources):
            if source.name in ('css_property_parser_gen.c','autogenerated-element-type.c'):continue
            obj=target/(source.relative_to(library).as_posix().replace('/','_')+'.o')
            command=['clang',*flags,'-I'+str(library/'src'),'-I'+str(library/'bindings'),'-c',str(source),'-o',str(obj)]
            print('COMMAND '+subprocess.list2cmdline(command),flush=True)
            subprocess.run(command,cwd=ROOT,check=True);objects.append(str(obj))
        archive=output/(name+'.a');subprocess.run(['llvm-ar','rcs',str(archive),*objects],check=True)
        print(f'WEB_LIBRARY {name} objects={len(objects)} bytes={archive.stat().st_size}',flush=True)
        archives.append(archive)
    stamp.write_text(key)
    return archives
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--output',required=True);parser.add_argument('--native',action='store_true')
    args=parser.parse_args();build(args.output,args.native)
