"""Generate kernel/sample_media.h: tiny demo PNG / animated GIF / PKV clip
embedded so the OS can drop sample media onto a fresh desktop. Reproducible:
run `python tools/gen_sample_media.py`."""
import io
import struct
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]


def png_bytes():
    im = Image.new("RGB", (256, 160))
    d = ImageDraw.Draw(im)
    for y in range(160):
        for x in range(256):
            im.putpixel((x, y), (x, y, (x + y) // 2 % 256))
    d.rectangle((16, 16, 240, 144), outline=(255, 255, 255), width=3)
    d.ellipse((96, 48, 160, 112), fill=(255, 220, 80))
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def gif_bytes():
    frames = []
    for i in range(6):
        f = Image.new("RGBA", (160, 120), (18, 22, 34, 255))
        d = ImageDraw.Draw(f)
        x = 20 + i * 20
        d.ellipse((x, 40, x + 40, 80), fill=(90, 170, 255, 255))
        d.rectangle((0, 100, 160, 120), fill=(40, 60, 100, 255))
        frames.append(f)
    buf = io.BytesIO()
    frames[0].save(buf, format="GIF", save_all=True, append_images=frames[1:],
                   duration=140, loop=0, disposal=2)
    return buf.getvalue()


def pkv_bytes():
    frames = []
    for i in range(8):
        im = Image.new("RGB", (176, 128), (12, 16, 28))
        d = ImageDraw.Draw(im)
        y = 20 + abs((i % 8) - 4) * 12
        d.ellipse((70, y, 106, y + 36), fill=(255, 90, 90))
        d.rectangle((0, 108, 176, 128), fill=(30, 44, 70))
        buf = io.BytesIO()
        im.save(buf, format="JPEG", quality=80)
        frames.append(buf.getvalue())
    header = b"PKV1" + struct.pack("<HHHH", 176, 128, len(frames), 120)
    table = b""
    off = len(header) + len(frames) * 8
    for fr in frames:
        table += struct.pack("<II", off, len(fr))
        off += len(fr)
    return header + table + b"".join(frames)


def c_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join(str(b) for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    png, gif, pkv = png_bytes(), gif_bytes(), pkv_bytes()
    out = []
    out.append("/* Generated by tools/gen_sample_media.py: demo media on the desktop. */")
    out.append("#ifndef POLLIK_SAMPLE_MEDIA_H")
    out.append("#define POLLIK_SAMPLE_MEDIA_H")
    out.append(c_array("sample_png", png))
    out.append(c_array("sample_gif", gif))
    out.append(c_array("sample_pkv", pkv))
    out.append("typedef struct { const char *name; const unsigned char *data; unsigned len; } SampleMedia;")
    out.append("static const SampleMedia sample_media[] = {")
    out.append('    {"photo.png", sample_png, sizeof(sample_png)},')
    out.append('    {"animation.gif", sample_gif, sizeof(sample_gif)},')
    out.append('    {"film.pkv", sample_pkv, sizeof(sample_pkv)},')
    out.append("};")
    out.append("#endif")
    (ROOT / "kernel" / "sample_media.h").write_text("\n".join(out) + "\n", encoding="ascii")
    print(f"wrote kernel/sample_media.h (png={len(png)} gif={len(gif)} pkv={len(pkv)})")


if __name__ == "__main__":
    main()
